[package]
name = "benches"
version = "0.0.1"
publish = false
edition = "2018"

[workspace]
members = ["."]

[dependencies]
buf-min = { path = "../.", features = ["bytes-buf-tokio3"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "buf-min"
harness = false
path = "src/all.rs"
